About Us
The eCourts Project was conceptualized on the basis of the "National Policy and Action Plan for Implementation of Information and Communication Technology (ICT) in the Indian Judiciary - 2005" submitted by eCommittee, Supreme Court of India with a vision to transform the Indian Judiciary by ICT enablement of Courts.

Ecommittee is a body constituted by the Government of India in pursuance of a proposal received from Hon'ble the Chief Justice of India to constitute an eCommittee to assist him in formulating a National policy on computerization of Indian Judiciary and advise on technological communication and management related changes.

The eCourts Mission Mode Project, is a Pan-India Project, monitored and funded by Department of Justice, Ministry of Law and Justice, Government of India for the District Courts across the country.

THE PROJECT ENVISAGES
To provide efficient & time-bound citizen centric services delivery as detailed in eCourt Project Litigant's Charter.
To develop, install & implement decision support systems in courts.
To automate the processes to provide transparency in accessibility of information to its stakeholders.
To enhance judicial productivity, both qualitatively & quantitatively, to make the justice delivery system affordable, accessible, cost effective, predictable, reliable and transparent.
Phase-I :
In Phase-I of the eCourts Project beginning from 2007, a large number of Court Complexes, Computer Server Rooms and Judicial Service Centres were readied for computerization of the District Courts. The District and Taluka Court Complexes covered in Phase-I were computerized with installation of hardware, LAN and Case Information Software (CIS), for providing basic case related services to the litigants and the lawyers. A large number of District Courts launched their websites for the convenience of the different stakeholders. The Change Management exercise was undertaken to train the Judicial Officers and Court Staff in the use of computers and Case Information System (CIS) was successfully implemented. The Judicial Officers were trained by the Master Trainers trained from amongst them for continuing training programme. The CIS Master trainers have trained District System Administrators (DSAs) in the use of CIS. The DSAs have trained all the Court Staff in the use of CIS. The data entry for all pending cases has reached an advanced stage of completion. The Process Re-Engineering exercise was initiated to have a fresh look on the process, procedures, systems and Court Rules in force in the different District Courts under High Courts. The Phase-I concluded with extended timelines upto 30th March 2015.

Phase II:
The Policy and Action Plan Document Phase-II of the ecourts Project, received approval of Hon'ble the Chief Justice of India on 8th January 2014. The government of India sanctioned the project on 4th August 2015. In Phase-II, the covered courts are provisioned for additional hardware with (1+3) systems per Court Room, the uncovered Courts of Phase-I and the newly established Courts with (2+6) systems per Court Room and the Court Complexes are provisioned for hardware, LAN etc.

The dynamic implementation structure provides for greater participation and cooperation between the eCommittee, the Department of Justice (Government of India), NIC, DietY and Ministry of finance. It provides for High Courts as Implementing Agency, of the project under its jurisdiction. The Infrastructure Model provides for adopting Cloud Computing Architecture which is efficient and cost effective, while retaining the present Servers Rooms as Network Rooms and Judicial Service centers as Centralized Filing Centres. Provision has been made for computerization of office of District Legal Services Authority; Taluka Legal Services Committee, the National Judicial Academy and the State Judicial Academies for efficient delivery of services and training.

Continuing with the implementation of Free and Open Source Solutions (FOSS), Phase-II has adopted the Core-Periphery model of Case Information Software, the core being Unified as National Core, while the periphery developed according to requirement of each High Court, with NIC, Pune continuing to be the Centre for Software Development and related applications, ensuring software compatibility and interoperability, both horizontally and vertically, with the data including metadata to be unified and standardized.

In Phase-II, all the remaining Court Complexes are provisioned to be connected with Jails and Desktop based Video Conferencing to go beyond routine remands and production of under-trial prisoners. It will also be used for recording evidence in sensitive cases and gradually extended to cover as many types of cases as possible. With an emphasis on Capacity Building of Judicial Officers and Process Re-Engineering, the Phase-II provides for Judicial Knowledge Management System including Integrated Library Management System and use of Digital Libraries.

The Phase-II of the project lays great emphasis on service delivery to the litigants, lawyers and other stakeholders. The websites will be Accessible Compliant and to the extent possible, the information will be available in the local languages. The applications for mobile phones , SMS and emails are extensively used as platforms for dissemination of information. Kiosk will be provided for every Court Complex. Certified copies of documents will be given online and ePayment Gateways will be provided for making deposits, payment of court fees, fines etc. The National Judicial Data Grid (NJDG) will be further improvised to facilitate more qualitative information for Courts, Government and Public.

ecourts.gov.in :
On 7th August 2013, Hon'ble the Chief Justice of India launched the e-Courts National portal ecourts.gov.in of the eCourts Project. More than 2852 Districts and Taluka Court Complexes have secured their presence on the NJDG portal ecourts.gov.in and are providing Case Status, Cause lists online with many of them also uploading orders/judgments. The data of more than 7 crore pending and disposed of cases and 3.3 crore orders/judgments of District Courts in India is available on NJDG at present.

With dynamic real time data generated and updated continuously, the NJDG is serving as a source of information of judicial delivery system for all the stakeholders. It is regularly analyzed for meaningful assistance in policy formation and decision making. The NJDG is working as National data warehouse for case data including the orders/judgments for Courts across the country with full coverage of District Courts.

The Online Analytical Processing, and Business Intelligence Tools will help in the summation of multiple databases into tables with summarized reports for preparation of informative management system and dashboards for effective Court and Case Management. The Judicial Management Information System will be helpful in litigations and adjudication pattern analysis and also the impact analysis of any variation in governing factors relating to law, amendments, jurisdiction, recruitment etc. It will also serve as judicial performance enhancing measure for policy makers to be used for decision support system.

***